### ISSUE TITLE
Example of form with several fields and a binary file

### ISSUE THREAD

**Issue by vbocan** [jacob-pro/actix-easy-multipart#8]
As of now, the example shows how to handle a multipart form that has just one text field:
`#[derive(MultipartForm)]
struct Upload {
    text: Text<String>,
}`
Could you please update the example or create a new one showing how to handle a form that has several text fields and a binary file? This is the typical example of a user using a form to submit some information alongside a binary file.
@jacob-pro, this is valuable work, should be pulled into the official actix web multipart package.

**Comment by jacob-pro** [comment]
Completed in https://github.com/jacob-pro/actix-easy-multipart/pull/9
